### ISSUE TITLE
Unable to export stats?

### ISSUE THREAD

**Issue by summertrove** [fbattarra/wp-quiz-pro-exporter#1]
Hi!

I've downloaded and activated the plugin.
I couldn't see the list of quizzes in the drop down list for exporting of data though.
See image: http://postimg.org/image/6ck3e4n13/

Thanks!

**Comment by ingyanees** [comment]
Hi, i have the same exact problem.hope if there could be a solution for this, it would be a very helpful plugin. Many thanks.

**Comment by fbattarra** [comment]
Hello summertrove & ingyanees, and thank you for giving my (sub)plugin a try! 

I just found the catch and pushed the fix (involving /admin/partials/*.php files): the table prefix was hardcoded in the queries instead of being retrieved dynamically. 

Can you please try again with the new files and give me your feedback?

Thank you in advance - and thank you SO much for helping me fixing stupid bugs :)
